spring:
  redis:
    password: 123456
    timeout: 5000
    ###################以下为redis哨兵增加的配置###########################
    sentinel:
      nodes: 192.168.76.128:26379,192.168.76.128:26380,192.168.76.128:26381
      master: mymaster
    ###################以下为lettuce连接池增加的配置###########################
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000